"use client";

import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, Database, FlaskConical, Gauge, GitCompareArrows, Route, Settings2, Upload, Download, Play, AlertTriangle } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";
const COLORS = ["#007f7a", "#2164a6", "#db6b24", "#8f4b9b", "#7a9327", "#be3f43"];
type AnyRow = Record<string, any>;
type Page = "upload" | "overview" | "analysis" | "latency" | "ilp" | "goal" | "comparison" | "sensitivity" | "routing" | "export";

async function api(path: string, options?: RequestInit) {
  let response: Response;
  try {
    response = await fetch(`${API}${path}`, options);
  } catch {
    throw new Error(`The FastAPI backend is unreachable at ${API}. Install Python, start the API on port 8000, then try again.`);
  }
  const body = await response.json();
  if (!response.ok) throw new Error(body.detail || "Request failed");
  return body;
}
const money = (value?: number) => value == null ? "-" : `$${value.toFixed(4)}`;
const decimal = (value?: number) => value == null ? "-" : value.toFixed(4);

export default function Dashboard() {
  const [page, setPage] = useState<Page>("upload"); const [summary, setSummary] = useState<AnyRow | null>(null); const [stats, setStats] = useState<AnyRow | null>(null); const [validation, setValidation] = useState<AnyRow | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<AnyRow | null>(null); const [comparison, setComparison] = useState<AnyRow[]>([]); const [routing, setRouting] = useState<AnyRow[]>([]); const [routingTotal, setRoutingTotal] = useState(0); const [search, setSearch] = useState(""); const [sensitivity, setSensitivity] = useState<AnyRow[]>([]);
  const [latency, setLatency] = useState({ fixed_overhead:.2, prompt_coefficient:.001, completion_coefficient:.002 }); const [ilp, setIlp] = useState({ minimum_quality:.85, maximum_average_latency:2 }); const [goal, setGoal] = useState({ target_cost:10, target_quality:.85, target_latency:2, cost_weight:.34, quality_weight:.33, latency_weight:.33 }); const [sensitivityForm, setSensitivityForm] = useState({ parameter:"minimum_quality", start:.75, end:.95, step:.05 });
  const modelStats = stats?.models || [];
  const refresh = async () => { try { const [nextSummary,nextStats] = await Promise.all([api("/dataset/summary"),api("/dataset/statistics")]); setSummary(nextSummary);setStats(nextStats); } catch { /* Dataset is optional until uploaded. */ } };
  useEffect(() => { refresh(); }, []);
  const run = async (action: () => Promise<any>) => { setBusy(true);setError(""); try { const data = await action(); setResult(data); await refresh(); return data; } catch(e:any) { setError(e.message); } finally { setBusy(false); } };
  const loadSample = () => run(async()=>{ const data=await api("/dataset/load-sample",{method:"POST"});setValidation(data.validation);return data; });
  const uploadFiles = async (files: FileList | null) => { if(!files?.length)return; await run(async()=>{const form=new FormData();Array.from(files).forEach(file=>form.append("files",file));const data=await api("/upload",{method:"POST",body:form});setValidation(data.validation);return data;}); };
  const runIlp = () => run(async()=>{const data=await api("/optimize/ilp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(ilp)});setResult(data);return data;});
  const runGoal = () => run(async()=>{const data=await api("/optimize/goal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(goal)});setResult(data);return data;});
  const runBaselines = () => run(async()=>{await Promise.all(["cheapest","quality","latency"].map(kind=>api(`/baseline/${kind}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(ilp)})));const data=await api("/results/comparison");setComparison(data.comparison);return data;});
  const getRouting = async (strategy="ilp", pageNo=1) => { try {const data=await api(`/results/routing?strategy=${strategy}&page=${pageNo}&page_size=25&search=${encodeURIComponent(search)}`);setRouting(data.items);setRoutingTotal(data.total);}catch(e:any){setError(e.message);} };
  const nav = [{id:"upload",label:"Dataset upload",icon:Upload},{id:"overview",label:"Dataset overview",icon:Database},{id:"analysis",label:"Statistical analysis",icon:BarChart3},{id:"latency",label:"Latency configuration",icon:Settings2},{id:"ilp",label:"ILP optimization",icon:Gauge},{id:"goal",label:"Goal programming",icon:FlaskConical},{id:"comparison",label:"Baseline comparison",icon:GitCompareArrows},{id:"sensitivity",label:"Sensitivity analysis",icon:BarChart3},{id:"routing",label:"Query routing",icon:Route},{id:"export",label:"Export",icon:Download}] as const;
  const content = useMemo(() => {
    if(page === "upload") return <><Header title="Dataset upload" subtitle="Load one or more JSON, CSV, or XLSX model benchmark files."/><div className="upload"><Upload size={30}/><p><label htmlFor="files">Choose benchmark files</label> or drop them here</p><small>JSON, CSV, XLSX. Each file may represent a model; records are aligned by query ID, origin query, or query.</small><input id="files" type="file" accept=".json,.csv,.xlsx,.xls" multiple onChange={e=>uploadFiles(e.target.files)}/></div><div className="actions"><button className="btn secondary" onClick={loadSample} disabled={busy}><Database size={16}/> Load repository sample</button></div>{validation && <Validation data={validation}/>}</>;
    if(!summary) return <Empty onLoad={loadSample} busy={busy}/>;
    if(page === "overview") return <><Header title="Dataset overview" subtitle="Measured benchmark quality and cost, plus calculated synthetic latency."/><Kpis summary={summary}/><div className="grid two" style={{marginTop:16}}><ChartPanel title="Average quality by model"><Bars data={modelStats} dataKey="average_quality"/></ChartPanel><ChartPanel title="Average cost by model"><Bars data={modelStats} dataKey="average_cost"/></ChartPanel><ChartPanel title="Total token usage by model"><Bars data={modelStats} dataKey="total_tokens"/></ChartPanel><ChartPanel title="Average synthetic latency by model"><Bars data={modelStats} dataKey="average_latency"/></ChartPanel></div></>;
    if(page === "analysis") return <><Header title="Statistical analysis" subtitle="Model-level descriptive statistics from the uploaded records."/><div className="grid three"><ChartPanel title="Cost vs quality"><ScatterPlot data={stats?.scatter || []} x="cost" y="quality"/></ChartPanel><ChartPanel title="Cost vs synthetic latency"><ScatterPlot data={stats?.scatter || []} x="cost" y="latency"/></ChartPanel><ChartPanel title="Quality vs synthetic latency"><ScatterPlot data={stats?.scatter || []} x="quality" y="latency"/></ChartPanel></div><StatsTable rows={modelStats}/></>;
    if(page === "latency") return <><Header title="Latency configuration" subtitle="Synthetic Latency = T0 + alpha × prompt tokens + beta × completion tokens. This is an estimate, not observed API latency."/><div className="panel"><div className="form-grid"><NumberField label="Fixed overhead T0" value={latency.fixed_overhead} onChange={v=>setLatency({...latency,fixed_overhead:v})}/><NumberField label="Prompt coefficient alpha" value={latency.prompt_coefficient} step="0.0001" onChange={v=>setLatency({...latency,prompt_coefficient:v})}/><NumberField label="Completion coefficient beta" value={latency.completion_coefficient} step="0.0001" onChange={v=>setLatency({...latency,completion_coefficient:v})}/></div><div className="actions"><button className="btn" disabled={busy} onClick={()=>run(async()=>api("/latency/configure",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(latency)}))}><Play size={16}/> Recalculate latency</button></div></div><div className="grid two" style={{marginTop:16}}><ChartPanel title="Average synthetic latency by model"><Bars data={modelStats} dataKey="average_latency"/></ChartPanel><StatsTable rows={modelStats.map((r:AnyRow)=>({model:r.model,minimum_latency:r.minimum_latency,average_latency:r.average_latency,maximum_latency:r.maximum_latency}))}/></div></>;
    if(page === "ilp") return <><Header title="ILP optimization" subtitle="Binary Integer Programming: minimize actual query-model cost while enforcing dataset-level quality and synthetic-latency constraints."/><div className="panel"><div className="form-grid"><NumberField label="Minimum average quality" value={ilp.minimum_quality} step=".01" onChange={v=>setIlp({...ilp,minimum_quality:v})}/><NumberField label="Maximum average synthetic latency" value={ilp.maximum_average_latency} step=".1" onChange={v=>setIlp({...ilp,maximum_average_latency:v})}/></div><div className="actions"><button className="btn" onClick={runIlp} disabled={busy}><Play size={16}/> Run ILP optimization</button></div></div><Result result={result}/></>;
    if(page === "goal") return <><Header title="Goal programming" subtitle="Minimize normalized undesirable deviations from the cost, quality, and synthetic-latency targets."/><div className="panel"><div className="form-grid"><NumberField label="Target total cost" value={goal.target_cost} onChange={v=>setGoal({...goal,target_cost:v})}/><NumberField label="Target average quality" value={goal.target_quality} step=".01" onChange={v=>setGoal({...goal,target_quality:v})}/><NumberField label="Target average latency" value={goal.target_latency} step=".1" onChange={v=>setGoal({...goal,target_latency:v})}/><NumberField label="Cost weight" value={goal.cost_weight} step=".01" onChange={v=>setGoal({...goal,cost_weight:v})}/><NumberField label="Quality weight" value={goal.quality_weight} step=".01" onChange={v=>setGoal({...goal,quality_weight:v})}/><NumberField label="Latency weight" value={goal.latency_weight} step=".01" onChange={v=>setGoal({...goal,latency_weight:v})}/></div><div className="actions"><span className={Math.abs(goal.cost_weight+goal.quality_weight+goal.latency_weight-1)<.0001?"badge":"badge bad"}>Weight sum: {(goal.cost_weight+goal.quality_weight+goal.latency_weight).toFixed(2)}</span><button className="btn" onClick={runGoal} disabled={busy}><Play size={16}/> Run goal programming</button></div></div><Result result={result}/></>;
    if(page === "comparison") return <><Header title="Baseline comparison" subtitle="Compare calculated single-model strategies against saved ILP and goal-programming results."/><button className="btn" disabled={busy} onClick={runBaselines}><Play size={16}/> Calculate baselines</button><div style={{marginTop:16}}><ComparisonTable rows={comparison}/></div></>;
    if(page === "sensitivity") return <><Header title="Sensitivity analysis" subtitle="Re-run optimization across constraints or standard goal-weight scenarios. Infeasible cases remain visible."/><div className="panel"><div className="form-grid"><label className="field">Parameter<select value={sensitivityForm.parameter} onChange={e=>setSensitivityForm({...sensitivityForm,parameter:e.target.value})}><option value="minimum_quality">Minimum quality</option><option value="maximum_latency">Maximum latency</option><option value="goal_weights">Goal weights</option></select></label>{sensitivityForm.parameter!=="goal_weights" && <><NumberField label="Start" value={sensitivityForm.start} step=".01" onChange={v=>setSensitivityForm({...sensitivityForm,start:v})}/><NumberField label="End" value={sensitivityForm.end} step=".01" onChange={v=>setSensitivityForm({...sensitivityForm,end:v})}/><NumberField label="Step" value={sensitivityForm.step} step=".01" onChange={v=>setSensitivityForm({...sensitivityForm,step:v})}/></>}</div><div className="actions"><button className="btn" disabled={busy} onClick={()=>run(async()=>{const data=await api("/sensitivity",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...sensitivityForm,ilp,goal})});setSensitivity(data.runs);return data;})}><Play size={16}/> Run sensitivity</button></div></div>{sensitivity.length>0&&<><ChartPanel title="Parameter value vs total cost"><ResponsiveContainer width="100%" height={280}><BarChart data={sensitivity}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="parameter_value"/><YAxis/><Tooltip/><Bar dataKey="total_cost" fill="#007f7a"/></BarChart></ResponsiveContainer></ChartPanel><ComparisonTable rows={sensitivity}/></>}</>;
    if(page === "routing") return <><Header title="Query routing" subtitle="Search and page through the chosen optimization result. Raw model responses remain on the backend."/><div className="panel"><div className="controls"><input placeholder="Search query or ID" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn secondary" onClick={()=>getRouting()}>Load ILP routing</button></div><div className="scroll"><table><thead><tr><th>Query ID</th><th>Query</th><th>Selected model</th><th>Quality</th><th>Cost</th><th>Tokens</th><th>Synthetic latency</th></tr></thead><tbody>{routing.map(row=><tr key={row.query_id}><td>{row.query_id}</td><td>{String(row.query||"").slice(0,170)}</td><td>{row.model}</td><td>{decimal(row.quality)}</td><td>{money(row.cost)}</td><td>{row.total_tokens}</td><td>{decimal(row.latency)}</td></tr>)}</tbody></table></div><p className="muted">{routingTotal} matching routes</p></div></>;
    return <><Header title="Export" subtitle="Download calculated routing, comparison, sensitivity, and dataset summary CSV files."/><div className="panel"><div className="actions"><a className="btn" href={`${API}/export?kind=routing&strategy=ilp`}><Download size={16}/> Routing CSV</a><a className="btn secondary" href={`${API}/export?kind=comparison`}><Download size={16}/> Comparison CSV</a><a className="btn secondary" href={`${API}/export?kind=sensitivity`}><Download size={16}/> Sensitivity CSV</a><a className="btn secondary" href={`${API}/export?kind=summary`}><Download size={16}/> Summary CSV</a></div></div></>;
  },[page,summary,stats,validation,busy,result,comparison,routing,routingTotal,search,sensitivity,latency,ilp,goal,sensitivityForm]);
  return <div className="shell"><aside className="side"><div className="brand"><span className="brand-mark"><Route size={18}/></span><span>Cost-Aware<br/>LLM Routing</span></div><nav className="nav">{nav.map(item=>{const Icon=item.icon;return <button key={item.id} className={page===item.id?"active":""} onClick={()=>setPage(item.id)}><Icon size={16}/>{item.label}</button>})}</nav></aside><main className="main"><header className="topbar"><h1>Operations Research Workspace</h1><span className="latency-note"><AlertTriangle size={14}/> Synthetic latency only</span></header><div className="content">{error&&<div className="status error">{error}</div>}{content}</div></main></div>;
}

function Header({title,subtitle}:{title:string;subtitle:string}){return <div className="section-head"><div><h2>{title}</h2><p>{subtitle}</p></div></div>}
function NumberField({label,value,onChange,step=".01"}:{label:string;value:number;onChange:(v:number)=>void;step?:string}){return <label className="field">{label}<input type="number" value={value} step={step} min="0" onChange={e=>onChange(Number(e.target.value))}/></label>}
function Empty({onLoad,busy}:{onLoad:()=>void;busy:boolean}){return <><Header title="No dataset loaded" subtitle="Upload benchmark results or load the repository sample to begin."/><button className="btn" onClick={onLoad} disabled={busy}><Database size={16}/> Load repository sample</button></>}
function Validation({data}:{data:AnyRow}){return <div className={data.valid?"status":"status error"}><b>{data.valid?"Dataset validation passed":"Dataset validation needs attention"}</b><div>Queries: {data.queries||0} | Complete queries: {data.complete_queries||0} | Models: {data.models?.length||0} | Records: {data.records||0}</div>{data.errors?.map((x:string)=><div key={x}>{x}</div>)}{data.warnings?.map((x:string)=><div className="warning" key={x}>{x}</div>)}</div>}
function Kpis({summary}:{summary:AnyRow}){const cards=[["Queries",summary.queries],["Models",summary.models],["Records",summary.records],["Total cost",money(summary.total_cost)],["Average quality",decimal(summary.average_quality)],["Total tokens",summary.total_tokens?.toLocaleString()],["Avg synthetic latency",decimal(summary.average_latency)]];return <div className="grid kpis">{cards.map(([label,value])=><div className="kpi" key={String(label)}><span>{label}</span><b>{value}</b></div>)}</div>}
function ChartPanel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h3>{title}</h3><div className="chart">{children}</div></section>}
function Bars({data,dataKey}:{data:AnyRow[];dataKey:string}){return <ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="model" tick={{fontSize:11}}/><YAxis/><Tooltip/><Bar dataKey={dataKey} fill="#007f7a"/></BarChart></ResponsiveContainer>}
function ScatterPlot({data,x,y}:{data:AnyRow[];x:string;y:string}){return <ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid/><XAxis type="number" dataKey={x} name={x}/><YAxis type="number" dataKey={y} name={y}/><Tooltip cursor={{strokeDasharray:"3 3"}}/><Scatter data={data} fill="#db6b24"/></ScatterChart></ResponsiveContainer>}
function StatsTable({rows}:{rows:AnyRow[]}){if(!rows.length)return null;const cols=Object.keys(rows[0]);return <section className="panel" style={{marginTop:16}}><h3>Model statistics</h3><div className="scroll"><table><thead><tr>{cols.map(col=><th key={col}>{col.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.model||i}>{cols.map(col=><td key={col}>{typeof row[col]==="number"?decimal(row[col]):String(row[col]??"")}</td>)}</tr>)}</tbody></table></div></section>}
function Result({result}:{result:AnyRow|null}){if(!result)return null;const good=result.status==="Optimal"||result.status==="Calculated";return <section className={`panel result ${good?"":"infeasible"}`} style={{marginTop:16}}><h3><span className={good?"badge":"badge bad"}>{result.status}</span></h3>{result.message&&<p>{result.message}</p>}{result.diagnostics&&<p className="muted">Highest achievable quality: {decimal(result.diagnostics.highest_achievable_quality)} | Lowest achievable latency: {decimal(result.diagnostics.lowest_achievable_latency)} | Cheapest possible cost: {money(result.diagnostics.cheapest_possible_cost)}</p>}{good&&<><div className="metrics"><div className="metric"><span>Total cost</span><b>{money(result.total_cost)}</b></div><div className="metric"><span>Average quality</span><b>{decimal(result.average_quality)}</b></div><div className="metric"><span>Average synthetic latency</span><b>{decimal(result.average_latency)}</b></div><div className="metric"><span>Objective</span><b>{decimal(result.objective_value)}</b></div></div>{result.deviations&&<p className="muted">Undesirable deviations: Cost {decimal(result.deviations.cost)}, Quality {decimal(result.deviations.quality)}, Latency {decimal(result.deviations.latency)}</p>}<div className="allocation">{Object.entries(result.model_allocation||{}).map(([model,value]:[string,any])=><div key={model}><b>{model}</b><br/><span className="muted">{value.queries} queries ({value.percentage}%)</span></div>)}</div></>}</section>}
function ComparisonTable({rows}:{rows:AnyRow[]}){if(!rows.length)return <section className="panel"><span className="muted">No calculated comparison results yet.</span></section>;return <section className="panel"><div className="scroll"><table><thead><tr><th>Strategy / parameter</th><th>Status</th><th>Total cost</th><th>Average quality</th><th>Average synthetic latency</th></tr></thead><tbody>{rows.map((row,i)=><tr key={i}><td>{row.strategy||row.parameter_value}</td><td><span className={row.status==="Optimal"||row.status==="Calculated"?"badge":"badge bad"}>{row.status}</span></td><td>{money(row.total_cost)}</td><td>{decimal(row.average_quality)}</td><td>{decimal(row.average_latency)}</td></tr>)}</tbody></table></div></section>}
